/** Exact English → Spanish names for common exercises. */
const EXACT_NAMES: Record<string, string> = {
  'push-up': 'Flexión',
  'push up': 'Flexión',
  'pull-up': 'Dominada',
  'pull up': 'Dominada',
  'chin-up': 'Dominada supina',
  'chin up': 'Dominada supina',
  'sit-up': 'Abdominal',
  'sit up': 'Abdominal',
  plank: 'Plancha',
  burpee: 'Burpee',
  'jumping jack': 'Jumping jack',
  'mountain climber': 'Escalador',
  'high knees': 'Rodillas altas',
  'box jump': 'Salto al cajón',
  'jump squat': 'Sentadilla con salto',
  'glute bridge': 'Puente de glúteos',
  'hip thrust': 'Empuje de cadera',
  'leg press': 'Prensa de piernas',
  'bench press': 'Press de banca',
  'incline bench press': 'Press inclinado',
  'decline bench press': 'Press declinado',
  'overhead press': 'Press militar',
  'shoulder press': 'Press de hombros',
  deadlift: 'Peso muerto',
  squat: 'Sentadilla',
  lunge: 'Zancada',
  'barbell curl': 'Curl con barra',
  'dumbbell curl': 'Curl con mancuerna',
  'hammer curl': 'Curl martillo',
  'triceps extension': 'Extensión de tríceps',
  'tricep extension': 'Extensión de tríceps',
  'lat pulldown': 'Jalón al pecho',
  'cable row': 'Remo en polea',
  'bent over row': 'Remo inclinado',
  'face pull': 'Face pull',
  'lateral raise': 'Elevación lateral',
  'front raise': 'Elevación frontal',
  'reverse fly': 'Apertura inversa',
  'chest fly': 'Apertura de pecho',
  'leg curl': 'Curl femoral',
  'leg extension': 'Extensión de cuádriceps',
  'calf raise': 'Elevación de gemelos',
  'romanian deadlift': 'Peso muerto rumano',
  'good morning': 'Good morning',
  'farmer walk': 'Paseo del granjero',
  'farmer carry': 'Paseo del granjero',
  'russian twist': 'Giro ruso',
  'bicycle crunch': 'Crunch bicicleta',
  'side plank': 'Plancha lateral',
  'wall sit': 'Sentadilla isométrica en pared',
  'jump rope': 'Salto a la comba',
  'battle rope': 'Cuerda de batalla',
  'kettlebell swing': 'Swing con kettlebell',
  'clean and press': 'Cargada y press',
  snatch: 'Arrancada',
  'power clean': 'Cargada de potencia',
}

/** Word-level glossary applied when no exact match exists (longest keys first). */
const TERM_GLOSSARY: Record<string, string> = {
  'bench press': 'press de banca',
  'overhead press': 'press militar',
  'shoulder press': 'press de hombros',
  'incline press': 'press inclinado',
  'decline press': 'press declinado',
  'push-up': 'flexión',
  'push up': 'flexión',
  'pull-up': 'dominada',
  'pull up': 'dominada',
  'chin-up': 'dominada supina',
  'sit-up': 'abdominal',
  'sit up': 'abdominal',
  deadlift: 'peso muerto',
  squat: 'sentadilla',
  lunge: 'zancada',
  plank: 'plancha',
  stretch: 'estiramiento',
  warmup: 'calentamiento',
  'warm-up': 'calentamiento',
  'warm up': 'calentamiento',
  curl: 'curl',
  row: 'remo',
  press: 'press',
  fly: 'apertura',
  raise: 'elevación',
  extension: 'extensión',
  crunch: 'crunch',
  pulldown: 'jalón',
  'pull-down': 'jalón',
  kickback: 'patada',
  shrug: 'encogimiento',
  swing: 'swing',
  snatch: 'arrancada',
  clean: 'cargada',
  jerk: 'envión',
  bridge: 'puente',
  thrust: 'empuje',
  rotation: 'rotación',
  twist: 'giro',
  hold: 'isométrico',
  walk: 'caminata',
  carry: 'transporte',
  jump: 'salto',
  skip: 'salto',
  run: 'carrera',
  sprint: 'sprint',
  bike: 'bici',
  cycling: 'ciclismo',
  rowing: 'remo',
  swimming: 'natación',
  barbell: 'barra',
  dumbbell: 'mancuerna',
  kettlebell: 'kettlebell',
  cable: 'polea',
  machine: 'máquina',
  band: 'banda',
  assisted: 'asistido',
  weighted: 'con lastre',
  incline: 'inclinado',
  decline: 'declinado',
  seated: 'sentado',
  standing: 'de pie',
  lying: 'tumbado',
  kneeling: 'de rodillas',
  single: 'a una pierna',
  double: 'a dos piernas',
  alternating: 'alterno',
  reverse: 'inverso',
  lateral: 'lateral',
  front: 'frontal',
  rear: 'posterior',
  side: 'lateral',
  upper: 'superior',
  lower: 'inferior',
  inner: 'interno',
  outer: 'externo',
  wide: 'ancho',
  narrow: 'estrecho',
  close: 'cerrado',
  grip: 'agarre',
  leg: 'pierna',
  legs: 'piernas',
  arm: 'brazo',
  arms: 'brazos',
  chest: 'pecho',
  back: 'espalda',
  shoulder: 'hombro',
  shoulders: 'hombros',
  neck: 'cuello',
  calf: 'gemelo',
  calves: 'gemelos',
  hamstring: 'isquio',
  hamstrings: 'isquios',
  glute: 'glúteo',
  glutes: 'glúteos',
  quad: 'cuádriceps',
  quads: 'cuádriceps',
  ab: 'abdominal',
  abs: 'abdominales',
  core: 'core',
  hip: 'cadera',
  hips: 'caderas',
  ankle: 'tobillo',
  wrist: 'muñeca',
  elbow: 'codo',
  knee: 'rodilla',
  toe: 'dedo del pie',
  foot: 'pie',
  hand: 'mano',
  hands: 'manos',
}

const SORTED_TERMS = Object.entries(TERM_GLOSSARY).sort((a, b) => b[0].length - a[0].length)

function normalizeKey(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, ' ')
}

function capitalizePhrase(text: string): string {
  return text.replace(/(^|\s)(\p{L})/gu, (_, space, letter) => `${space}${letter.toUpperCase()}`)
}

/** Offline English → Spanish exercise name (glossary + exact matches). */
export function translateExerciseName(nameEn: string): string {
  const key = normalizeKey(nameEn)
  const exact = EXACT_NAMES[key]
  if (exact) return exact

  let translated = nameEn
  for (const [en, es] of SORTED_TERMS) {
    translated = translated.replace(new RegExp(`\\b${escapeRegExp(en)}\\b`, 'gi'), es)
  }

  return capitalizePhrase(translated)
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
